export const ROUTING = {
  BASE: '/',
  BRUKERE: '/brukere',
  BRUKER: '/bruker',
  SDA: '/sda',
  LDA: '/lda',
  ADMIN: '/amdinistrasjon',
  ROLLER: '/roller',
  ROLLE: '/rolle',
  STAMMER: '/stammer',
  STAMME: '/stamme',
  REGISTRERINGER: '/registreringer',
  REGISTRERING: '/registrering',
  TILGANGER: '/tilganger',
  TILGANG: '/tilgang',
  EKSISTERENDE_TILGANGER: '/eksisterendetilganger',
  UTGAATTE_TILGANGER: '/utgaattetilganger',
  ONSKES_SLETTET_TILGANGER: '/onskesslettettilganger',
  VISENDRETILGANG: '/visendretilgang',
  VISREGISTRERING: '/visregistrering',
  NYREGISTRERING: '/nyregistrering',
  UBEHANDLEDEREG: '/ubehandlederegistreringer',
  UBEHANDLEDLINUXFORLENG: '/ubehandledelinuxforlengelser'
}
